import License from '#models/license'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await License.query().delete()

    await License.createMany([
      {
        title: 'Basic License',
        description: 'MP3, WAV, and stems license for standard releases.',
        isPaypalEnabled: true,
        isActive: true,
        sortOrder: 10,
        priceCents: 2990,
        isTemplate: true,
        templateCategory: 'basic',
        audioFormats: ['mp3', 'wav'],
        trackSeparation: 'stems',
        maxStreams: 500000,
        maxSales: 2000,
        radioStations: 2,
        allowVideoClips: true,
        videoClipsLimit: 1,
        allowLivePerformance: true,
        allowRadioAirplay: true,
        allowTelevision: false,
        allowRemix: false,
        allowMonetization: false,
        allowContentId: false,
        additionalTerms: 'Includes MP3, WAV, and track-by-track stems.',
      },
      {
        title: 'Premium License',
        description: 'MP3, WAV, and stems license for larger monetized releases.',
        isPaypalEnabled: true,
        isActive: true,
        sortOrder: 20,
        priceCents: 4990,
        isTemplate: true,
        templateCategory: 'premium',
        audioFormats: ['mp3', 'wav'],
        trackSeparation: 'stems',
        maxStreams: 500000,
        maxSales: 3000,
        radioStations: 2,
        allowVideoClips: true,
        videoClipsLimit: 1,
        allowLivePerformance: true,
        allowRadioAirplay: true,
        allowTelevision: false,
        allowRemix: false,
        allowMonetization: true,
        allowContentId: true,
        additionalTerms: 'Includes MP3, WAV, stems, and monetization rights.',
      },
      {
        title: 'Premium Plus License',
        description: 'MP3, WAV, and stems license with wider usage rights.',
        isPaypalEnabled: true,
        isActive: true,
        sortOrder: 30,
        priceCents: 7990,
        isTemplate: true,
        templateCategory: 'premium_plus',
        audioFormats: ['mp3', 'wav'],
        trackSeparation: 'stems',
        maxStreams: 500000,
        maxSales: 10000,
        radioStations: 2,
        allowVideoClips: true,
        videoClipsLimit: 1,
        allowLivePerformance: true,
        allowRadioAirplay: true,
        allowTelevision: false,
        allowRemix: true,
        allowMonetization: true,
        allowContentId: true,
        additionalTerms: 'Includes MP3, WAV, stems, remix rights, and monetization.',
      },
      {
        title: 'Exclusive Rights',
        description: 'Exclusive purchase handled manually through quote and negotiation.',
        isPaypalEnabled: false,
        isActive: true,
        sortOrder: 40,
        priceCents: 0,
        isTemplate: true,
        templateCategory: 'exclusive',
        audioFormats: null,
        trackSeparation: null,
        maxStreams: null,
        maxSales: null,
        radioStations: null,
        allowVideoClips: true,
        videoClipsLimit: null,
        allowLivePerformance: true,
        allowRadioAirplay: true,
        allowTelevision: true,
        allowRemix: true,
        allowMonetization: true,
        allowContentId: true,
        additionalTerms: 'Exclusive rights are negotiated case by case.',
      },
    ])
  }
}
