/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type LicenseTransformer from '#transformers/license_transformer'
import type MusicalKeyTransformer from '#transformers/musical_key_transformer'
import type TagTransformer from '#transformers/tag_transformer'
import type TrackTransformer from '#transformers/track_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type License = InferData<LicenseTransformer>
  export namespace License {
    export type Variants = InferVariants<LicenseTransformer>
  }
  export type MusicalKey = InferData<MusicalKeyTransformer>
  export namespace MusicalKey {
    export type Variants = InferVariants<MusicalKeyTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type Track = InferData<TrackTransformer>
  export namespace Track {
    export type Variants = InferVariants<TrackTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
