/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  ClientDashboard: () => import('#controllers/client_dashboard_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Licenses: () => import('#controllers/licenses_controller'),
  MusicalKeys: () => import('#controllers/musical_keys_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PaypalPayments: () => import('#controllers/paypal_payments_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Tags: () => import('#controllers/tags_controller'),
  TrackLicenses: () => import('#controllers/track_licenses_controller'),
  Tracks: () => import('#controllers/tracks_controller'),
}
