/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DownloadAccessSchema extends BaseModel {
  static $columns = ['accessToken', 'createdAt', 'downloadCount', 'expiresAt', 'fileType', 'id', 'licenseId', 'paymentOrderId', 'trackId', 'updatedAt', 'userId'] as const
  $columns = DownloadAccessSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloadCount: number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare fileType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licenseId: number
  @column()
  declare paymentOrderId: number
  @column()
  declare trackId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class LicenseSchema extends BaseModel {
  static $columns = ['additionalTerms', 'allowContentId', 'allowLivePerformance', 'allowMonetization', 'allowRadioAirplay', 'allowRemix', 'allowTelevision', 'allowVideoClips', 'audioFormats', 'createdAt', 'description', 'id', 'isActive', 'isPaypalEnabled', 'isTemplate', 'maxSales', 'maxStreams', 'priceCents', 'radioStations', 'sortOrder', 'templateCategory', 'title', 'trackSeparation', 'updatedAt', 'userId', 'videoClipsLimit'] as const
  $columns = LicenseSchema.$columns
  @column()
  declare additionalTerms: string | null
  @column()
  declare allowContentId: boolean
  @column()
  declare allowLivePerformance: boolean
  @column()
  declare allowMonetization: boolean
  @column()
  declare allowRadioAirplay: boolean
  @column()
  declare allowRemix: boolean
  @column()
  declare allowTelevision: boolean
  @column()
  declare allowVideoClips: boolean
  @column()
  declare audioFormats: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isPaypalEnabled: boolean
  @column()
  declare isTemplate: boolean
  @column()
  declare maxSales: bigint | number | null
  @column()
  declare maxStreams: bigint | number | null
  @column()
  declare priceCents: number
  @column()
  declare radioStations: number | null
  @column()
  declare sortOrder: number
  @column()
  declare templateCategory: string | null
  @column()
  declare title: string
  @column()
  declare trackSeparation: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare videoClipsLimit: number | null
}

export class MusicalKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = MusicalKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentOrderSchema extends BaseModel {
  static $columns = ['amountCents', 'capturePayload', 'createdAt', 'currencyCode', 'errorPayload', 'id', 'licenseId', 'licenseIdSnapshot', 'licenseTitleSnapshot', 'orderPayload', 'payerEmail', 'paypalCaptureId', 'paypalOrderId', 'provider', 'requestPayload', 'status', 'trackId', 'trackTitleSnapshot', 'updatedAt', 'userId'] as const
  $columns = PaymentOrderSchema.$columns
  @column()
  declare amountCents: number
  @column()
  declare capturePayload: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column()
  declare errorPayload: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licenseId: number | null
  @column()
  declare licenseIdSnapshot: number | null
  @column()
  declare licenseTitleSnapshot: string
  @column()
  declare orderPayload: string | null
  @column()
  declare payerEmail: string | null
  @column()
  declare paypalCaptureId: string | null
  @column()
  declare paypalOrderId: string | null
  @column()
  declare provider: string
  @column()
  declare requestPayload: string | null
  @column()
  declare status: string
  @column()
  declare trackId: number | null
  @column()
  declare trackTitleSnapshot: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'type', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackLicenseSchema extends BaseModel {
  static $columns = ['createdAt', 'isActive', 'licenseId', 'priceCents', 'trackId', 'updatedAt'] as const
  $columns = TrackLicenseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare isActive: boolean
  @column()
  declare licenseId: number
  @column()
  declare priceCents: number
  @column()
  declare trackId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackTagSchema extends BaseModel {
  static $columns = ['createdAt', 'tagId', 'trackId', 'updatedAt'] as const
  $columns = TrackTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare tagId: number
  @column()
  declare trackId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackSchema extends BaseModel {
  static $columns = ['audioFilePath', 'bpm', 'coverImagePath', 'createdAt', 'durationSeconds', 'id', 'isActive', 'isSold', 'listenCount', 'musicalKeyId', 'priceCents', 'soldAt', 'title', 'updatedAt', 'waveFilePath', 'zipFilePath'] as const
  $columns = TrackSchema.$columns
  @column()
  declare audioFilePath: string | null
  @column()
  declare bpm: number | null
  @column()
  declare coverImagePath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationSeconds: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isSold: boolean
  @column()
  declare listenCount: number
  @column()
  declare musicalKeyId: number | null
  @column()
  declare priceCents: number
  @column.dateTime()
  declare soldAt: DateTime | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare waveFilePath: string | null
  @column()
  declare zipFilePath: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
