/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DownloadAccessSchema extends BaseModel {
  static $columns = ['accessToken', 'createdAt', 'downloadCount', 'expiresAt', 'fileType', 'id', 'licenseId', 'paymentOrderId', 'trackId', 'updatedAt', 'userId'] as const
  $columns = DownloadAccessSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloadCount: number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare fileType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licenseId: number
  @column()
  declare paymentOrderId: number
  @column()
  declare trackId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class LicenseSchema extends BaseModel {
  static $columns = ['additionalTerms', 'allowAdultContent', 'allowCommercialUse', 'allowContentId', 'allowEducationalUse', 'allowGamblingUse', 'allowLivePerformance', 'allowMechanicalRepro', 'allowMilitaryUse', 'allowMonetization', 'allowNonprofitUse', 'allowOfflineListening', 'allowPodcast', 'allowPoliticalUse', 'allowRadioAirplay', 'allowReligiousUse', 'allowRemix', 'allowRemixDistribution', 'allowSampling', 'allowStreaming', 'allowSublicense', 'allowTelevision', 'allowTrackModification', 'allowTransfer', 'allowVideoClips', 'allowedPlatforms', 'allowedTerritories', 'audioFormats', 'commercialUseDescription', 'commercialUseLimit', 'createdAt', 'creditRequirements', 'description', 'durationMonths', 'id', 'isActive', 'isExclusive', 'isPaypalEnabled', 'isTemplate', 'licenseEndDate', 'licenseStartDate', 'masterSplitPercentage', 'maxConcurrentStreams', 'maxDownloads', 'maxSales', 'maxStreams', 'minAudioBitrate', 'modificationRestrictions', 'priceCents', 'publishingSplitPercentage', 'radioStations', 'requireApprovalForModification', 'requireArtistCredit', 'requireDrmEncryption', 'requireMasterCredit', 'requirePublishingCredit', 'requiresWrittenAgreement', 'restrictedGenres', 'restrictedUseCases', 'revisionDate', 'revisionNotes', 'sortOrder', 'templateCategory', 'thirdPartySplitPercentage', 'title', 'trackSeparation', 'transferRestrictions', 'updatedAt', 'userId', 'videoClipsLimit'] as const
  $columns = LicenseSchema.$columns
  @column()
  declare additionalTerms: string | null
  @column()
  declare allowAdultContent: boolean
  @column()
  declare allowCommercialUse: boolean
  @column()
  declare allowContentId: boolean
  @column()
  declare allowEducationalUse: boolean
  @column()
  declare allowGamblingUse: boolean
  @column()
  declare allowLivePerformance: boolean
  @column()
  declare allowMechanicalRepro: boolean
  @column()
  declare allowMilitaryUse: boolean
  @column()
  declare allowMonetization: boolean
  @column()
  declare allowNonprofitUse: boolean
  @column()
  declare allowOfflineListening: boolean
  @column()
  declare allowPodcast: boolean
  @column()
  declare allowPoliticalUse: boolean
  @column()
  declare allowRadioAirplay: boolean
  @column()
  declare allowReligiousUse: boolean
  @column()
  declare allowRemix: boolean
  @column()
  declare allowRemixDistribution: boolean
  @column()
  declare allowSampling: boolean
  @column()
  declare allowStreaming: boolean
  @column()
  declare allowSublicense: boolean
  @column()
  declare allowTelevision: boolean
  @column()
  declare allowTrackModification: boolean
  @column()
  declare allowTransfer: boolean
  @column()
  declare allowVideoClips: boolean
  @column()
  declare allowedPlatforms: any | null
  @column()
  declare allowedTerritories: any | null
  @column()
  declare audioFormats: any | null
  @column()
  declare commercialUseDescription: string | null
  @column()
  declare commercialUseLimit: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditRequirements: string | null
  @column()
  declare description: string | null
  @column()
  declare durationMonths: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isExclusive: boolean
  @column()
  declare isPaypalEnabled: boolean
  @column()
  declare isTemplate: boolean
  @column.dateTime()
  declare licenseEndDate: DateTime | null
  @column.dateTime()
  declare licenseStartDate: DateTime | null
  @column()
  declare masterSplitPercentage: string
  @column()
  declare maxConcurrentStreams: number | null
  @column()
  declare maxDownloads: bigint | number | null
  @column()
  declare maxSales: bigint | number | null
  @column()
  declare maxStreams: bigint | number | null
  @column()
  declare minAudioBitrate: string | null
  @column()
  declare modificationRestrictions: string | null
  @column()
  declare priceCents: number
  @column()
  declare publishingSplitPercentage: string
  @column()
  declare radioStations: number | null
  @column()
  declare requireApprovalForModification: boolean
  @column()
  declare requireArtistCredit: boolean
  @column()
  declare requireDrmEncryption: boolean
  @column()
  declare requireMasterCredit: boolean
  @column()
  declare requirePublishingCredit: boolean
  @column()
  declare requiresWrittenAgreement: boolean
  @column()
  declare restrictedGenres: string | null
  @column()
  declare restrictedUseCases: string | null
  @column.dateTime()
  declare revisionDate: DateTime | null
  @column()
  declare revisionNotes: string | null
  @column()
  declare sortOrder: number
  @column()
  declare templateCategory: string | null
  @column()
  declare thirdPartySplitPercentage: string
  @column()
  declare title: string
  @column()
  declare trackSeparation: string | null
  @column()
  declare transferRestrictions: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare videoClipsLimit: number | null
}

export class MusicalKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = MusicalKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column()
  declare userId: number
}

export class PaymentOrderSchema extends BaseModel {
  static $columns = ['amountCents', 'capturePayload', 'createdAt', 'currencyCode', 'errorPayload', 'id', 'licenseId', 'licenseIdSnapshot', 'licenseTitleSnapshot', 'orderPayload', 'payerEmail', 'paypalCaptureId', 'paypalOrderId', 'provider', 'requestPayload', 'status', 'trackId', 'trackTitleSnapshot', 'updatedAt', 'userId'] as const
  $columns = PaymentOrderSchema.$columns
  @column()
  declare amountCents: number
  @column()
  declare capturePayload: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column()
  declare errorPayload: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licenseId: number | null
  @column()
  declare licenseIdSnapshot: number | null
  @column()
  declare licenseTitleSnapshot: string
  @column()
  declare orderPayload: string | null
  @column()
  declare payerEmail: string | null
  @column()
  declare paypalCaptureId: string | null
  @column()
  declare paypalOrderId: string | null
  @column()
  declare provider: string
  @column()
  declare requestPayload: string | null
  @column()
  declare status: string
  @column()
  declare trackId: number | null
  @column()
  declare trackTitleSnapshot: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'type', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackLicenseSchema extends BaseModel {
  static $columns = ['createdAt', 'isActive', 'licenseId', 'priceCents', 'trackId', 'updatedAt'] as const
  $columns = TrackLicenseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare isActive: boolean
  @column()
  declare licenseId: number
  @column()
  declare priceCents: number
  @column()
  declare trackId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackTagSchema extends BaseModel {
  static $columns = ['createdAt', 'tagId', 'trackId', 'updatedAt'] as const
  $columns = TrackTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare tagId: number
  @column()
  declare trackId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackSchema extends BaseModel {
  static $columns = ['audioFilePath', 'bpm', 'coverImagePath', 'createdAt', 'durationSeconds', 'id', 'isActive', 'isSold', 'listenCount', 'musicalKeyId', 'priceCents', 'soldAt', 'title', 'updatedAt', 'waveFilePath', 'zipFilePath'] as const
  $columns = TrackSchema.$columns
  @column()
  declare audioFilePath: string | null
  @column()
  declare bpm: number | null
  @column()
  declare coverImagePath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationSeconds: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isSold: boolean
  @column()
  declare listenCount: number
  @column()
  declare musicalKeyId: number | null
  @column()
  declare priceCents: number
  @column.dateTime()
  declare soldAt: DateTime | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare waveFilePath: string | null
  @column()
  declare zipFilePath: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
